//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

[assembly: AssemblyTitle("Grapevine")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyCompany("Scott Offen")]
[assembly: AssemblyProduct("Grapevine")]
[assembly: AssemblyVersion("4.1.0.0")]
[assembly: AssemblyFileVersion("4.1.0.0")]
[assembly: AssemblyInformationalVersion("4.0.0.196")]
[assembly: AssemblyCopyright("© 2014-2016 Scott Offen")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyConfiguration("")]
[assembly: Guid("f6ac4c2c-4801-465c-8dd4-932dc1890747")]

[assembly: InternalsVisibleTo("Grapevine.Tests")]

